-- Seed 50 factors with icons
INSERT INTO factors (name, icon, description) VALUES
('Tài chính', '💰', 'Lợi ích tài chính và chi phí liên quan'),
('Thời gian', '⏰', 'Thời gian cần thiết và thời gian thực hiện'),
('Mức độ stress', '😰', 'Mức độ căng thẳng và áp lực'),
('Rủi ro', '⚠️', 'Mức độ rủi ro và khả năng thất bại'),
('Cơ hội', '🚀', 'Cơ hội phát triển và tiềm năng'),
('Mức độ yêu thích', '❤️', 'Mức độ hứng thú và yêu thích cá nhân'),
('Sức khỏe', '🏥', 'Tác động đến sức khỏe thể chất và tinh thần'),
('Gia đình', '👨‍👩‍👧‍👦', 'Ảnh hưởng đến gia đình và các mối quan hệ thân thiết'),
('Bạn bè', '👥', 'Ảnh hưởng đến các mối quan hệ bạn bè'),
('Sự nghiệp', '💼', 'Tác động đến sự nghiệp và phát triển nghề nghiệp'),
('Học tập', '📚', 'Cơ hội học hỏi và phát triển kiến thức'),
('Địa điểm', '📍', 'Vị trí địa lý và không gian làm việc'),
('Môi trường làm việc', '🏢', 'Môi trường và văn hóa làm việc'),
('Thu nhập', '💵', 'Thu nhập tiềm năng và lợi ích kinh tế'),
('Chi phí', '💸', 'Chi phí đầu vào và chi phí vận hành'),
('Lợi ích dài hạn', '📈', 'Lợi ích trong tương lai dài hạn'),
('Lợi ích ngắn hạn', '⚡', 'Lợi ích ngay lập tức và ngắn hạn'),
('Độ khó', '🎯', 'Mức độ khó khăn và thách thức'),
('Mức độ hỗ trợ', '🤝', 'Sự hỗ trợ từ người khác và nguồn lực'),
('Tính khả thi', '✅', 'Khả năng thực hiện và tính khả thi'),
('Độ linh hoạt', '🔄', 'Khả năng thích ứng và linh hoạt'),
('Tác động xã hội', '🌍', 'Ảnh hưởng đến cộng đồng và xã hội'),
('Tác động môi trường', '🌱', 'Ảnh hưởng đến môi trường và bền vững'),
('Đổi mới sáng tạo', '💡', 'Cơ hội sáng tạo và đổi mới'),
('Sự ổn định', '🏛️', 'Mức độ ổn định và an toàn'),
('Tiềm năng tăng trưởng', '📊', 'Khả năng mở rộng và phát triển'),
('Cân bằng cuộc sống', '⚖️', 'Cân bằng giữa công việc và cuộc sống'),
('Độ phù hợp với giá trị', '🎭', 'Sự phù hợp với giá trị cá nhân'),
('Độ phù hợp với kỹ năng', '🛠️', 'Sự phù hợp với kỹ năng và năng lực'),
('Cơ hội networking', '🔗', 'Cơ hội mở rộng mạng lưới quan hệ'),
('Uy tín', '⭐', 'Uy tín và danh tiếng'),
('Tự do', '🕊️', 'Mức độ tự chủ và tự do'),
('Độc lập', '🏝️', 'Khả năng hoạt động độc lập'),
('Quyền lực', '👑', 'Mức độ ảnh hưởng và quyền lực'),
('Ảnh hưởng', '📢', 'Khả năng tạo ra ảnh hưởng'),
('An toàn', '🛡️', 'Mức độ an toàn và bảo mật'),
('Bảo mật', '🔒', 'Bảo mật thông tin và dữ liệu'),
('Độ tin cậy', '✓', 'Độ tin cậy và uy tín'),
('Chất lượng', '💎', 'Chất lượng sản phẩm hoặc dịch vụ'),
('Tốc độ', '⏩', 'Tốc độ thực hiện và hiệu quả'),
('Hiệu quả', '🎯', 'Hiệu quả và năng suất'),
('Sự tiện lợi', '🛋️', 'Sự tiện lợi và dễ sử dụng'),
('Trải nghiệm người dùng', '😊', 'Trải nghiệm và sự hài lòng'),
('Khả năng mở rộng', '📦', 'Khả năng mở rộng quy mô'),
('Tính bảo trì', '🔧', 'Dễ dàng bảo trì và sửa chữa'),
('Tài nguyên sẵn có', '📦', 'Tài nguyên và nguồn lực có sẵn'),
('Thời gian thị trường', '🕐', 'Thời điểm phù hợp với thị trường'),
('Cạnh tranh', '⚔️', 'Mức độ cạnh tranh và vị thế'),
('Khách hàng', '👤', 'Khách hàng mục tiêu và thị trường'),
('Thị trường mục tiêu', '🎯', 'Phân khúc thị trường và khách hàng');
